---
- name: server are provisioned in vpc
  hosts: localhost
  gather_facts: false
  vars:
     #ec2_vpcidr: 10.251.0.0/16
     #ec2_stack_name: "project1"
     #ec2_subnetcidr: 10.251.1.0/24
     #ec2_region: "eu-west-1"
     #ec2_az: a
     #ec2_exact_count: 1
     #ec2_key_name: "project1"
     

- name: server are provisioned in vpc
  hosts: docker-swarm-master
  gather_facts: false
  
  tasks:

  - name: Init a new swarm with default parameters
    docker_swarm:
      state: present
