---
  - name: execute shell command
    shell: hostname
  
  - name: install docker-py using pip
    pip:
      name: docker-py
    with_items: "{{ groups['docker-swarm-node'] }}"
      
  - name: install docker using yum
    yum:
      name: docker
      state: present
    with_items: "{{ groups['docker-swarm-node'] }}"

  - name: start docker service
    service:
      name: docker
      state: started 
    with_items: "{{ groups['docker-swarm-node'] }}"  

  #- name: join worker node to dockerswarm manager
  #  shell:  docker swarm join --token "{{ hostvars['docker-swarm-master']['swarm_node_token'] }}"  "{{ groups['docker-swarm-master'] }}:2377"
  #  with_items: "{{ groups['docker-swarm-node'] }}"

  - name: Add workers to docker swarm manager
    docker_swarm:
      state: join
      join_token: "{{ hostvars[groups['docker-swarm-master'][0]].master['swarm_facts']['JoinTokens']['Worker'] }}"
      advertise_addr: "{{ item }}"
      remote_addrs: "{{ groups['docker-swarm-master'] }}"
    with_items: "{{ groups['docker-swarm-node'] }}"
