---
- name: server are provisioned in vpc
  hosts: localhost
  gather_facts: false
     
  tasks:
  - import_tasks: docker-swarm-cluster.yml
  
- name: configuring dockerswarm master
  hosts: docker-swarm-master
  become: True
  gather_facts: True
  
  tasks:   
  - import_tasks: dockerswarm-master-configure.yml 

- name: configuring dockerswarm node 
  hosts: docker-swarm-node
  become: True
  gather_facts: True
  
  tasks:
  - import_tasks: dockerswarm-node-configure.yml
